Project Setup
henask12/Blogify pull request #1
Opened 2023-09-26 22:57 UTC by henask12

**Pull Request Summary:**

## General Requirements

- [ ] Code is free of linter errors.
- [ ] Followed Gitflow workflow.

## Project Requirements

- [ ] Created a new app with a meaningful name.
- [ ] Initialized Git for version control.
- [ ] Set up PostgreSQL database.
- [ ] Designed and executed schema.

    - [ ] Followed ERD for naming.
    - [ ] Added foreign keys where necessary.
    - [ ] Created indexes for foreign keys.

2023-09-26 23:55 UTC, Whoistolu reviewed
Hi @henask12 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### You have submitted a project, that does not have the Microverse recommended professional README. Kindly add this as it is part of the project requirements.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @whoistolu in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-09-27 08:16 UTC, abdulhamiid requested changes
# Status: Required Changes :recycle:
Hi @henask12 👋, 
![Alt Text](https://c.tenor.com/vOLW_UQMySIAAAAC/almost-there.gif)
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights 🌟

- ✔️ Descriptions are descriptive
- ✔️ Install Ruby on Rails framework.
- ✔️ Use Ruby Gems as a software package system.

## Required Changes ♻️
_Please kindly check the comments under the review._

## Optional suggestions 🤷‍♂️
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

Cheers, and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-27 08:16 UTC, abdulhamiid commented on README.md
> +This project is [MIT](./MIT) licensed.
Please fix the broken license link for a professional repository 😊

2023-09-27 08:16 UTC, abdulhamiid commented on README.md
> +- LinkedIn: [LinkedIn](https://www.linkedin.com/in/henokmekonnen1)
![image](https://github.com/henask12/Blogify/assets/78251927/81cdddae-ed75-4b89-94cd-ebcc42f42219)

For a professional repository, let's avoid broken links in our readme, kindly fix the broken link in the `Authors` section 👍

2023-09-27 08:16 UTC, abdulhamiid commented on db/schema.rb
> +  end
The implementation and method name for the provided sample codes should work. 👀, but here, I am getting errors.

![image](https://github.com/henask12/Blogify/assets/78251927/f30d7200-a62b-4ebf-ad62-5f91461c815f)

`rails c` is the intended way to open a console for your app. It loads rails itself, all your `models`, and everything else needed.

I would suggest you create `user.rb` in `app/models/user.rb`

```ruby
class User < ApplicationRecord
end
```

As well as the remaining models, `post.rb`, `comment.rb` and `like.rb` for the app to work🤓🛠

2023-09-28 12:43 UTC, Felix45 approved these changes
# Approved :green_circle: 
Hi @henask12, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://user-images.githubusercontent.com/52934128/163691476-087b4b9c-825b-40a3-85a1-d1bde44ffa53.gif" width="250px" />

## Highlights :heavy_check_mark: 
- [x] All migrations setup correctly :white_check_mark: 
- [x] Application functions as expected :white_check_mark: 
- [x] Repository has a professional readme file :white_check_mark: 
- [x] Pull request has a descriptive title and summary :white_check_mark: 
- [x] Implemented all the changes from the previous reviewer :white_check_mark:     

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-28 12:54 UTC, merged